API_PREFXI = ""
ALLOWED_HOSTS = ['localhost']
HOST = "127.0.0.1"
PORT = 3000

POSTGRESQL_USER = "postgres"
POSTGRESQL_PASSWORD = "yourpassword"
POSTGRESQL_HOST = "localhost"
POSTGRESQL_PORT = "5432"
POSTGRESQL_DB = "postgres"
CONNECTION_STRING = f"postgresql+asyncpg://{POSTGRESQL_USER}:{POSTGRESQL_PASSWORD}@{POSTGRESQL_HOST}:{POSTGRESQL_PORT}/{POSTGRESQL_DB}"

